server:
  port: 1234
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://dev-admin.cotillioncloud.com:3306/cotillion_admin
    username: leena.philips
    password: '{cipher}f8184f0050273b1a9ce684ba7279c5ec7771b89f0c15b5c7a195d186c33ca33f'
    driver-class-name: com.mysql.jdbc.Driver
   #jpa:
    hibernate.ddl-auto: update

  jwt:
    tokenExpirationTime: 15 # Number of minutes
    refreshTokenExpTime: 60 # Minutes
    tokenIssuer: ME
    secret: ENC(bOaYyyr/9oHtd+TrWXpI3818rRl0Unxb)
jasypt:
  encryptor:
    password: '{cipher}f8184f0050273b1a9ce684ba7279c5ec7771b89f0c15b5c7a195d186c33ca33f'
  logging:
    level:
      org.springframework.security: DEBUG
  spring:
    contextPath: /manager
---
spring:
    profiles: production
